<?php
declare(strict_types=1);

return [
    // Produktive Hauptdomain. Kann auf dem Server über RAILTIME_SITE_URL überschrieben werden.
    'site_url' => rtrim((string)(getenv('RAILTIME_SITE_URL') ?: 'https://www.rail-time.de'), '/'),
    'site_name' => 'RT Rail Time GmbH',
    'locale' => 'de_DE',
    'language' => 'de-DE',
    'company' => 'RT Rail Time GmbH',
    'claim' => 'Ihr verlässlicher Partner für professionelle Wagenmeister-Dienstleistungen im Eisenbahngüterverkehr – sicher, flexibel, bundesweit und bei Bedarf rund um die Uhr.',
    'about_title' => 'Kompetent, flexibel und bundesweit im Einsatz',
    'about_copy' => 'Die RT Rail Time GmbH verbindet fachliche Kompetenz mit hoher Einsatzbereitschaft. 60+ erfahrene Wagenmeister unterstützen Kunden im Eisenbahngüterverkehr flexibel, präzise und bundesweit.',
    'emergency_title' => 'Kurzfristiger Einsatz erforderlich?',
    'emergency_copy' => 'Bei dringenden technischen Unregelmäßigkeiten erreichen Sie unseren Wagenmeister-Notfalldienst rund um die Uhr unter 0160 1881848.',
    'phone' => '0160 1881848',
    'phone_href' => '+491601881848',
    'email' => 'kontakt@rail-time.de',
    'address' => 'Borsteler Weg 29–31 · 21423 Winsen (Luhe)',
    'postal_address' => [
        'street' => 'Borsteler Weg 29–31',
        'postal_code' => '21423',
        'locality' => 'Winsen (Luhe)',
        'country' => 'DE',
    ],
    'navigation' => [
        ['route' => 'home', 'label' => 'Home'],
        ['route' => 'about', 'label' => 'Über uns'],
        ['route' => 'services', 'label' => 'Leistungen'],
        ['route' => 'contact', 'label' => 'Kontakt'],
        ['route' => 'imprint', 'label' => 'Impressum'],
        ['route' => 'privacy', 'label' => 'Datenschutz'],
    ],
    'assets' => [
        'hero_poster' => 'start3-first-frame.png',
        'hero_video' => 'start3.mp4',
        'service_images' => ['s3.jpg', 's2.jpg', '1.jpg', 's4.jpg', 'puffer_schmierungs_leistung.webp'],
    ],
    'metrics' => [
        ['number' => '60+', 'label' => 'Erfahrene Wagenmeister'],
        ['number' => '24/7', 'label' => 'Notfalldienst'],
        ['number' => 'DE', 'label' => 'Bundesweite Einsätze'],
    ],
    'process' => [
        'Einsatzort, Zeitraum und Aufgabenstellung werden aufgenommen.',
        'Qualifikation, Ausrüstung und Verfügbarkeit werden abgestimmt.',
        'Der Auftrag wird sicher und zuverlässig vor Ort bearbeitet.',
        'Ergebnis und weiteres Vorgehen werden transparent kommuniziert.',
    ],
    'equipment' => 'PSA · Mobiltelefon & GSM-R · Laptop & mobiler Drucker · Pufferfett · Gefahrgut-Placards · Spanngurte · Messgeräte · Panzertape · Luftbremskopf · Flex',
    'services' => [
        ['slug' => 'wagenmeister-dienstleistungen', 'title' => 'Wagenmeister-Dienstleistungen', 'copy' => 'Professionelle Prüfungen von Güterwagen sichern reibungslose Abläufe, dokumentierte Ergebnisse und hohe Standards im täglichen Betrieb.'],
        ['slug' => 'notfalldienst-24-7', 'title' => 'Notfalldienst 24/7', 'copy' => 'Kurzfristige Wagenmeister-Einsätze bei technischen Unregelmäßigkeiten – deutschlandweit, rund um die Uhr und zuverlässig koordiniert.'],
        ['slug' => 'kv-trailer-service', 'title' => 'KV- & Trailer-Service', 'copy' => 'Prüfung und Bearbeitung von Auffälligkeiten an verladenen LKW-Trailern für sichere Abläufe im kombinierten Eisenbahnverkehr.'],
        ['slug' => 'sonderuntersuchungen', 'title' => 'Sonderuntersuchungen', 'copy' => 'Detaillierte technische Untersuchungen an Güterwagen mit klarer Befundaufnahme, Bewertung und abgestimmtem weiteren Vorgehen.'],
        ['slug' => 'pufferteller-schmieren', 'title' => 'Pufferteller schmieren', 'copy' => 'Fachgerechtes Schmieren von Puffertellern mit mitgeführtem Pufferfett – direkt am Einsatzort und ohne unnötige Verzögerungen.'],
    ],
    'seo' => [
        'home' => [
            'title' => 'Wagenmeister-Dienstleistungen bundesweit | RT Rail Time',
            'description' => 'RT Rail Time bietet Wagenmeister-Dienstleistungen im Eisenbahngüterverkehr: 60+ erfahrene Wagenmeister, Notfalldienst 24/7 und bundesweite Einsätze.',
            'path' => '',
            'schema_type' => 'WebPage',
            'image' => 'start3-first-frame.jpg',
            'image_alt' => 'Wagenmeister von RT Rail Time im Eisenbahngüterverkehr',
        ],
        'services' => [
            'title' => 'Wagenmeister-Dienstleistungen & Notfalldienst | Rail Time',
            'description' => 'Wagenmeister-Dienstleistungen, Notfalldienst 24/7, KV- & Trailer-Service, Sonderuntersuchungen und Pufferteller schmieren – bundesweit im Einsatz.',
            'path' => 'leistungen',
            'schema_type' => 'CollectionPage',
            'image' => 's4.jpg',
            'image_alt' => 'Wagenmeister-Dienstleistungen der RT Rail Time GmbH',
        ],
        'about' => [
            'title' => 'Über RT Rail Time | Wagenmeister im Eisenbahngüterverkehr',
            'description' => 'RT Rail Time ist Ihr kompetenter, flexibler Partner für Wagenmeister-Dienstleistungen im Eisenbahngüterverkehr – sicher, zuverlässig und bundesweit.',
            'path' => 'ueber-uns',
            'schema_type' => 'AboutPage',
            'image' => 's3.jpg',
            'image_alt' => 'Mitarbeiter der RT Rail Time GmbH im Bahnbetrieb',
        ],
        'contact' => [
            'title' => 'Kontakt & Einsatzanfrage | RT Rail Time GmbH',
            'description' => 'Kontaktieren Sie RT Rail Time für Wagenmeister-Dienstleistungen und kurzfristige Einsätze. Notfalldienst 24/7: 0160 1881848, kontakt@rail-time.de.',
            'path' => 'kontakt',
            'schema_type' => 'ContactPage',
            'image' => 's1.jpg',
            'image_alt' => 'Kontakt zur RT Rail Time GmbH',
        ],
        'imprint' => [
            'title' => 'Impressum | RT Rail Time GmbH',
            'description' => 'Impressum der RT Rail Time GmbH mit Kontakt- und Unternehmensangaben.',
            'path' => 'impressum',
            'schema_type' => 'WebPage',
            'image' => 'logo-horizontal-darkbg.png',
            'image_alt' => 'Logo der RT Rail Time GmbH',
            'robots' => 'noindex,follow',
        ],
        'privacy' => [
            'title' => 'Datenschutzerklärung | RT Rail Time GmbH',
            'description' => 'Datenschutzerklärung der RT Rail Time GmbH mit Informationen zur Verarbeitung personenbezogener Daten auf dieser Website.',
            'path' => 'datenschutz',
            'schema_type' => 'WebPage',
            'image' => 'logo-horizontal-darkbg.png',
            'image_alt' => 'Logo der RT Rail Time GmbH',
            'robots' => 'noindex,follow',
        ],
        'not_found' => [
            'title' => 'Seite nicht gefunden | RT Rail Time GmbH',
            'description' => 'Die angeforderte Seite wurde nicht gefunden.',
            'path' => '404',
            'schema_type' => 'WebPage',
            'image' => 'logo-horizontal-darkbg.png',
            'image_alt' => 'Logo der RT Rail Time GmbH',
            'robots' => 'noindex,nofollow',
        ],
    ],
    'legal' => [
        // Diese Angaben müssen vor Veröffentlichung mit den rechtsverbindlichen Daten ergänzt werden.
        'managing_director' => '',
        'register_court' => '',
        'register_number' => '',
        'vat_id' => '',
        'liability_insurer' => '',
        'liability_insurer_address' => '',
        'hosting_provider' => '',
        'server_log_retention' => '',
    ],
    'mail' => [
        'enabled' => filter_var(getenv('RAILTIME_MAIL_ENABLED') ?: '1', FILTER_VALIDATE_BOOL),
        'recipient' => 'kontakt@rail-time.de',
        'from' => 'kontakt@rail-time.de',
        'subject_prefix' => '[Website-Anfrage]',
    ],
];
