<?php
require_once __DIR__.'/../site-shell.php';

function rt3_emergency(array $rt): void { ?>
<section class="ig-emergency ig-motion-up"><div><span class="ig-code">ALERT / 24-7</span><p class="ig-kicker">Notfalldienst 24/7</p><h2><?= $rt['emergency_title'] ?></h2><p><?= $rt['emergency_copy'] ?></p><a class="ig-button" href="tel:<?= $rt['phone_href'] ?>">Notfalldienst anrufen <b>↗</b></a></div><figure><img src="<?= rt_image('s2.jpg') ?>" alt="Technische Untersuchung am Güterwagen"><figcaption>Technische Unterstützung / bundesweit</figcaption></figure></section>
<?php }

function rt3_home(): void { $rt=rt_document_start('Industrial Grid',3,true); ?>
<main>
<section class="ig-hero rt-hero"><video <?= rt_video_attrs($rt) ?>><source src="<?= rt_video($rt['assets']['hero_video']) ?>" type="video/mp4"></video><div class="ig-hero__screen"></div><div class="rt-intro-logo"><span class="ig-target"></span><img src="<?= rt_image($rt['assets']['logo_dark']) ?>" alt="RT Rail Time GmbH"></div><div class="ig-hero__meta"><span>RT / RAIL SYSTEMS</span><span>DE / BUNDESWEIT</span><span>24 / 7</span></div></section>
<section class="ig-opening" id="content-start"><header class="ig-opening__head ig-motion-up"><span class="ig-code">RT-00 / EISENBAHNGÜTERVERKEHR</span><p class="ig-kicker">RT Rail Time GmbH</p><h1><?= $rt['claim'] ?></h1></header><div class="ig-opening__visual ig-motion-left"><img src="<?= rt_image('s3.jpg') ?>" alt="Wagenmeister im Einsatz"><span class="ig-corner top"></span><span class="ig-corner bottom"></span></div><aside class="ig-opening__data ig-motion-right"><?php foreach($rt['metrics'] as $i=>$metric): ?><div><small>0<?= $i+1 ?></small><strong><?= $metric['number'] ?></strong><span><?= $metric['label'] ?></span></div><?php endforeach ?><a class="ig-button" href="kontakt.html">Einsatz anfragen <b>↗</b></a></aside></section>
<section class="ig-services" id="leistungen"><header><div><span class="ig-code">MODULE / 01–05</span><p class="ig-kicker">Unsere Leistungen</p><h2>Fünf Leistungsbereiche für einen sicheren Eisenbahnbetrieb</h2></div><a href="leistungen.html">Alle Leistungen ↗</a></header><div class="ig-service-list"><?php foreach($rt['services'] as $i=>$service): ?><a class="ig-service ig-motion-<?= $i%2?'right':'left' ?>" href="leistungen.html#<?= $service['slug'] ?>"><span class="ig-service__no">0<?= $i+1 ?></span><figure><img src="<?= rt_image($rt['assets']['service_images'][$i]) ?>" alt="<?= htmlspecialchars($service['title'],ENT_QUOTES,'UTF-8') ?>"></figure><h3><?= $service['title'] ?></h3><small><?= $i===1?'24/7 verfügbar':'Bundesweit im Einsatz' ?></small><b>↗</b></a><?php endforeach ?></div></section>
<section class="ig-promise"><div><span>Sicher</span><i></i><span>Flexibel</span><i></i><span>Rund um die Uhr</span><i></i><span>Bundesweit im Einsatz</span></div></section>
<section class="ig-about"><div class="ig-about__copy ig-motion-left"><span class="ig-code">COMPANY / TEAM</span><p class="ig-kicker">Über RT Rail Time</p><h2><?= $rt['about_title'] ?></h2><p><?= $rt['about_copy'] ?></p><a class="ig-button light" href="ueber-uns.html">Unternehmen kennenlernen <b>↗</b></a></div><figure class="ig-motion-right"><img src="<?= rt_image('s4.jpg') ?>" alt="Rail Time Mitarbeiter im Bahnbetrieb"><figcaption><b>56+</b> qualifizierte Wagenmeister</figcaption></figure></section>
<section class="ig-process"><header><span class="ig-code">WORKFLOW / 04 STEPS</span><p class="ig-kicker">Zusammenarbeit</p><h2>Von der Anfrage bis zum zuverlässig ausgeführten Einsatz.</h2></header><div><?php foreach($rt['process'] as $i=>$step): ?><article class="ig-motion-up"><b>0<?= $i+1 ?></b><span></span><p><?= $step ?></p></article><?php endforeach ?></div></section>
<section class="ig-map"><div class="ig-map__module"><?php include __DIR__.'/../../modules/germany-map.php'; ?></div><aside class="ig-motion-right"><span class="ig-code">NETWORK / GERMANY</span><p class="ig-kicker">Ausrüstung &amp; Technik</p><h2>Für sichere und effiziente Einsätze vorbereitet</h2><p><?= $rt['equipment'] ?></p></aside></section>
<?php rt3_emergency($rt); ?>
</main><?php rt_footer($rt); rt_document_end(true); }

function rt3_services(): void { $rt=rt_document_start('Leistungen',3); ?>
<main class="ig-subpage"><section class="ig-page-hero" style="--image:url('<?= rt_image('s4.jpg') ?>')"><div><span class="ig-code">SERVICE SYSTEM / 01–05</span><p class="ig-kicker">Unsere Leistungen</p><h1>Leistungen für sichere Abläufe im Eisenbahngüterverkehr</h1><p>Professionelle Wagenmeister-Dienstleistungen, kurzfristige Notfalleinsätze und technische Unterstützung im kombinierten Verkehr.</p><a class="ig-button" href="kontakt.html">Einsatz anfragen <b>↗</b></a></div><aside><?php foreach($rt['metrics'] as $metric): ?><div><strong><?= $metric['number'] ?></strong><span><?= $metric['label'] ?></span></div><?php endforeach ?></aside></section>
<section class="ig-module-menu"><header><p class="ig-kicker">Leistungsbereiche</p><h2>Fünf Leistungen. Ein verlässlicher Ansprechpartner.</h2></header><div><?php foreach($rt['services'] as $i=>$service): ?><a data-service-tile href="#<?= $service['slug'] ?>"><span>0<?= $i+1 ?></span><img src="<?= rt_image($rt['assets']['service_images'][$i]) ?>" alt="<?= htmlspecialchars($service['title'],ENT_QUOTES,'UTF-8') ?>"><h3><?= $service['title'] ?></h3><b>↘</b></a><?php endforeach ?></div></section>
<section class="ig-accordion"><header><span class="ig-code">DETAIL / ACCORDION</span><p class="ig-kicker">Leistungen im Detail</p><h2>Strukturiert. Nachvollziehbar. Einsatzbereit.</h2></header><?php foreach($rt['services'] as $i=>$service): ?><article id="<?= $service['slug'] ?>" data-accordion-item><button type="button" aria-expanded="false"><span>0<?= $i+1 ?></span><strong><?= $service['title'] ?></strong><small><?= $i===1?'NOTFALL / 24-7':'SERVICE / DE' ?></small><i class="accordion-plus">+</i></button><div data-panel><div class="ig-panel"><img src="<?= rt_image($rt['assets']['service_images'][$i]) ?>" alt="<?= htmlspecialchars($service['title'],ENT_QUOTES,'UTF-8') ?>"><div><h3><?= $service['title'] ?></h3><p><?= $service['copy'] ?></p><ol><li>Anfrage und Einsatzdaten aufnehmen</li><li>Qualifikation und Ausrüstung abstimmen</li><li>Einsatz vor Ort durchführen</li><li>Befund und Rückmeldung dokumentieren</li></ol><a href="kontakt.html">Einsatz anfragen ↗</a></div></div></div></article><?php endforeach ?></section>
<section class="ig-process compact"><header><p class="ig-kicker">Ablauf</p><h2>Von der Anfrage bis zur Rückmeldung.</h2></header><div><?php foreach($rt['process'] as $i=>$step): ?><article><b>0<?= $i+1 ?></b><span></span><p><?= $step ?></p></article><?php endforeach ?></div></section><?php rt3_emergency($rt); ?></main><?php rt_footer($rt); rt_document_end(); }

function rt3_about(): void { $rt=rt_document_start('Über uns',3); ?>
<main class="ig-subpage"><section class="ig-page-hero" style="--image:url('<?= rt_image('s3.jpg') ?>')"><div><span class="ig-code">COMPANY / RAILTIME</span><p class="ig-kicker">Ihr Partner im Eisenbahnbetrieb</p><h1>Über RT Rail Time GmbH</h1><p>Kompetent, flexibel und mit höchstem Anspruch an Sicherheit, Qualität und Kundenzufriedenheit.</p><a class="ig-button" href="kontakt.html">Einsatz anfragen <b>↗</b></a></div><aside><?php foreach($rt['metrics'] as $metric): ?><div><strong><?= $metric['number'] ?></strong><span><?= $metric['label'] ?></span></div><?php endforeach ?></aside></section>
<section class="ig-about-detail"><figure><img src="<?= rt_image('s1.jpg') ?>" alt="Wagenmeister von RT Rail Time"><figcaption>RT / Mitarbeiter im Einsatz</figcaption></figure><div><span class="ig-code">PROFILE / 01</span><p class="ig-kicker">Im Detail</p><h2>Maßgeschneiderte Lösungen für den Eisenbahngüterverkehr.</h2><p>Die RT Rail Time GmbH ist Ihr kompetenter und flexibler Partner für Wagenmeister-Dienstleistungen im Eisenbahngüterverkehr. Mit hohem Anspruch an Sicherheit und Qualität bieten wir maßgeschneiderte Lösungen für unterschiedliche Herausforderungen im Bereich der Wagenmeisterdienstleistungen.</p><p>Unser Handeln ist auf die Zufriedenheit unserer Kunden ausgerichtet. Präzise Arbeitsweise, zuverlässige Kommunikation und schnelle Reaktion bilden die Grundlage unserer Zusammenarbeit.</p></div></section>
<section class="ig-values"><header><p class="ig-kicker">Unsere Philosophie</p><h2>Vertrauen entsteht durch transparente und zuverlässige Zusammenarbeit.</h2></header><div><article><b>01</b><h3>Sicherheit &amp; Qualität</h3><p>Nachhaltiges Qualitätsmanagement unterstützt Leistungen auf hohem fachlichem Niveau.</p></article><article><b>02</b><h3>Transparenz</h3><p>Klare Abstimmung und nachvollziehbare Kommunikation schaffen Vertrauen.</p></article><article><b>03</b><h3>Flexibilität</h3><p>Kurze Reaktionszeiten ermöglichen auch die Bearbeitung kurzfristiger Kundenanfragen.</p></article></div></section><section class="ig-process"><header><p class="ig-kicker">Zusammenarbeit</p><h2>Von der Anfrage bis zum zuverlässig ausgeführten Einsatz.</h2></header><div><?php foreach($rt['process'] as $i=>$step): ?><article><b>0<?= $i+1 ?></b><span></span><p><?= $step ?></p></article><?php endforeach ?></div></section><?php rt3_emergency($rt); ?></main><?php rt_footer($rt); rt_document_end(); }

function rt3_contact(): void { $rt=rt_document_start('Kontakt',3); ?>
<main class="ig-subpage"><section class="ig-page-hero" style="--image:url('<?= rt_image('s1.jpg') ?>')"><div><span class="ig-code">CONTACT / OPERATIONS</span><p class="ig-kicker">Kontakt &amp; Einsatzanfrage</p><h1>Direkt erreichbar. Deutschlandweit im Einsatz.</h1><p>Ob planbare Wagenmeister-Dienstleistung oder kurzfristiger Notfalleinsatz: Teilen Sie uns Einsatzort, gewünschte Leistung und Zeitpunkt mit.</p><a class="ig-button" href="tel:<?= $rt['phone_href'] ?>"><?= $rt['phone'] ?> <b>↗</b></a></div><aside><?php foreach($rt['metrics'] as $metric): ?><div><strong><?= $metric['number'] ?></strong><span><?= $metric['label'] ?></span></div><?php endforeach ?></aside></section>
<section class="ig-contact"><aside><span class="ig-code">REQUEST / NEW</span><p class="ig-kicker">Ihre Anfrage</p><h2>Schnelle Abstimmung für einen sicheren Eisenbahnbetrieb.</h2><p>Je vollständiger die Einsatzangaben sind, desto schneller können wir Ihre Anfrage einordnen und bearbeiten.</p><dl><div><dt>Notfalldienst 24/7</dt><dd><a href="tel:<?= $rt['phone_href'] ?>"><?= $rt['phone'] ?></a></dd></div><div><dt>E-Mail &amp; Einsatzanfrage</dt><dd><a href="mailto:<?= $rt['email'] ?>"><?= $rt['email'] ?></a></dd></div><div><dt>Firmensitz</dt><dd><?= $rt['address'] ?></dd></div></dl></aside><form action="mailto:<?= $rt['email'] ?>" method="post" enctype="text/plain"><header><b>RT / EINSATZANFRAGE</b><span>Pflichtfelder *</span></header><label>Name *<input name="Name" required></label><label>E-Mail *<input name="E-Mail" type="email" required></label><label>Telefon<input name="Telefon" type="tel"></label><label>Einsatzort<input name="Einsatzort"></label><label class="full">Gewünschte Leistung<select name="Leistung"><?php foreach($rt['services'] as $service): ?><option><?= $service['title'] ?></option><?php endforeach ?></select></label><label class="full">Nachricht *<textarea name="Nachricht" rows="6" required></textarea></label><button class="ig-button full" type="submit">Anfrage per E-Mail vorbereiten <b>↗</b></button></form></section><?php rt3_emergency($rt); ?></main><?php rt_footer($rt); rt_document_end(); }

function rt3_legal(string $type): void { $rt=rt_document_start($type==='imprint'?'Impressum':'Datenschutzerklärung',3); $imprint=$type==='imprint'; ?>
<main class="ig-subpage"><section class="ig-legal-hero"><span class="ig-code">LEGAL / <?= $imprint?'IMPRINT':'PRIVACY' ?></span><p class="ig-kicker">Rechtliches</p><h1><?= $imprint?'Impressum':'Datenschutzerklärung' ?></h1></section><article class="ig-legal"><?php if($imprint): ?><h2>Angaben gemäß § 5 TMG</h2><p>Handelsregister:</p><p>Registergericht:</p><p><strong>Vertreten durch:</strong></p><h2>Kontakt</h2><p>Telefon: <?= $rt['phone'] ?><br>E-Mail: <?= $rt['email'] ?></p><h2>Umsatzsteuer-ID</h2><h2>Angaben zur Berufshaftpflichtversicherung</h2><p><strong>Name und Sitz des Versicherers:</strong></p><h2>Verbraucherstreitbeilegung/Universalschlichtungsstelle</h2><p>Wir sind nicht bereit oder verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.</p><h2>Haftung für Inhalte</h2><p>Als Diensteanbieter sind wir gemäß § 7 Abs. 1 TMG für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich.</p><h2>Haftung für Links</h2><p>Unser Angebot enthält Links zu externen Websites Dritter, auf deren Inhalte wir keinen Einfluss haben.</p><h2>Urheberrecht</h2><p>Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht.</p><?php else: ?><h2>Datenschutz auf einen Blick</h2><h3>Allgemeine Hinweise</h3><p>Die folgenden Hinweise geben einen einfachen Überblick darüber, was mit Ihren personenbezogenen Daten passiert, wenn Sie diese Website besuchen.</p><h2>Datenerfassung auf dieser Website</h2><h3>Wer ist verantwortlich für die Datenerfassung?</h3><p>Die Datenverarbeitung auf dieser Website erfolgt durch den Websitebetreiber.</p><h3>Wie erfassen wir Ihre Daten?</h3><p>Ihre Daten werden zum einen dadurch erhoben, dass Sie uns diese mitteilen.</p><h3>Wofür nutzen wir Ihre Daten?</h3><p>Ein Teil der Daten wird erhoben, um eine fehlerfreie Bereitstellung der Website zu gewährleisten.</p><h2>Allgemeine Hinweise und Pflichtinformationen</h2><p>Die Betreiber dieser Seiten nehmen den Schutz Ihrer persönlichen Daten sehr ernst und behandeln personenbezogene Daten vertraulich.</p><h2>Kontaktformular</h2><p>Wenn Sie uns per Kontaktformular Anfragen zukommen lassen, werden Ihre Angaben zwecks Bearbeitung der Anfrage gespeichert und verarbeitet.</p><?php endif ?></article></main><?php rt_footer($rt); rt_document_end(); }
