<?php
require_once __DIR__.'/../site-shell.php';

function rt2_emergency(array $rt): void { ?>
<section class="sc-emergency sc-motion-rise"><div class="sc-emergency__image"><img src="<?= rt_image('s2.jpg') ?>" alt="Technische Untersuchung am Güterwagen"><span>24/7</span></div><div class="sc-emergency__copy"><p class="sc-kicker">Notfalldienst 24/7</p><h2><?= $rt['emergency_title'] ?></h2><p><?= $rt['emergency_copy'] ?></p><div class="sc-actions"><a class="sc-button" href="tel:<?= $rt['phone_href'] ?>">Notfalldienst anrufen ↗</a><a href="kontakt.html">Kontakt →</a></div></div></section>
<?php }

function rt2_home(): void { $rt=rt_document_start('Signal Compact',2,true); ?>
<main>
<section class="sc-hero rt-hero"><video <?= rt_video_attrs($rt) ?>><source src="<?= rt_video($rt['assets']['hero_video']) ?>" type="video/mp4"></video><div class="sc-hero__shade"></div><div class="rt-intro-logo"><span></span><img src="<?= rt_image($rt['assets']['logo_dark']) ?>" alt="RT Rail Time GmbH"></div><div class="sc-hero__status"><b>Deutschlandweit im Einsatz</b><i></i><b>24/7 Notfalldienst</b></div></section>
<section class="sc-opening" id="content-start"><div class="sc-opening__copy sc-motion-rise"><p class="sc-kicker">RT Rail Time GmbH</p><h1><?= $rt['claim'] ?></h1><div class="sc-actions"><a class="sc-button" href="leistungen.html">Leistungen ansehen ↗</a><a href="kontakt.html">Kontakt aufnehmen →</a></div></div><div class="sc-opening__image sc-motion-rise"><img src="<?= rt_image('s1.jpg') ?>" alt="Wagenmeister von RT Rail Time"><aside><strong>56+</strong><span>qualifizierte Wagenmeister</span></aside></div><div class="sc-metrics"><?php foreach($rt['metrics'] as $metric): ?><div><strong><?= $metric['number'] ?></strong><span><?= $metric['label'] ?></span></div><?php endforeach ?></div></section>
<section class="sc-services" id="leistungen"><header class="sc-heading sc-motion-rise"><div><p class="sc-kicker">Unsere Leistungen</p><h2>Fünf Leistungsbereiche für einen sicheren Eisenbahnbetrieb</h2></div><a href="leistungen.html">Alle Leistungen ↗</a></header><div class="sc-service-grid"><?php foreach($rt['services'] as $i=>$service): ?><a class="sc-service sc-service--<?= $i+1 ?> sc-motion-<?= $i%2?'right':'left' ?>" href="leistungen.html#<?= $service['slug'] ?>"><img src="<?= rt_image($rt['assets']['service_images'][$i]) ?>" alt="<?= htmlspecialchars($service['title'],ENT_QUOTES,'UTF-8') ?>"><span>0<?= $i+1 ?></span><div><small>Leistungsbereich</small><h3><?= $service['title'] ?></h3><b>Details öffnen ↗</b></div></a><?php endforeach ?></div></section>
<section class="sc-marquee" aria-label="Leistungsversprechen"><div><span>Sicher <i>✦</i> Flexibel <i>✦</i> Rund um die Uhr <i>✦</i> Bundesweit im Einsatz <i>✦</i></span><span aria-hidden="true">Sicher <i>✦</i> Flexibel <i>✦</i> Rund um die Uhr <i>✦</i> Bundesweit im Einsatz <i>✦</i></span></div></section>
<section class="sc-about"><div class="sc-about__image sc-motion-left"><img src="<?= rt_image('s4.jpg') ?>" alt="Rail Time Mitarbeiter im Bahnbetrieb"><span>RT / Einsatz</span></div><div class="sc-about__copy sc-motion-right"><p class="sc-kicker">Über RT Rail Time</p><h2><?= $rt['about_title'] ?></h2><p><?= $rt['about_copy'] ?></p><a class="sc-button dark" href="ueber-uns.html">Unternehmen kennenlernen ↗</a></div><div class="sc-qualities"><div><b>01</b><strong>Sicherheit &amp; Qualität</strong></div><div><b>02</b><strong>56+ Wagenmeister</strong></div><div><b>03</b><strong>Regelmäßig geschult</strong></div><div><b>04</b><strong>Schnell &amp; flexibel</strong></div></div></section>
<section class="sc-team"><div class="sc-team__copy sc-motion-left"><p class="sc-kicker">Unser Team</p><h2>56+ qualifizierte Wagenmeister – bundesweit verfügbar</h2><p>Unsere Mitarbeiter werden regelmäßig fortgebildet und vereinen Qualifikationen aus Wagenprüfung, Bahnbetrieb, Qualitätsmanagement, Gefahrgut und Schadwagenmanagement.</p><a href="ueber-uns.html">Mehr über Rail Time →</a></div><div class="sc-team__image sc-motion-right"><img src="<?= rt_image('s3.jpg') ?>" alt="Wagenmeister bei der Prüfung"></div></section>
<section class="sc-map"><div class="sc-map__intro"><p class="sc-kicker">Standorte &amp; Einsatzbereitschaft</p><h2>Für sichere und effiziente Einsätze vorbereitet</h2><p><?= $rt['equipment'] ?></p></div><div><?php include __DIR__.'/../../modules/germany-map.php'; ?></div></section>
<?php rt2_emergency($rt); ?>
</main><?php rt_footer($rt); rt_document_end(true); }

function rt2_services(): void { $rt=rt_document_start('Leistungen',2); ?>
<main class="sc-subpage"><section class="sc-page-hero" style="--image:url('<?= rt_image('s4.jpg') ?>')"><div><p class="sc-kicker">Unsere Leistungen</p><h1>Leistungen für sichere Abläufe im Eisenbahngüterverkehr</h1><p>Professionelle Wagenmeister-Dienstleistungen, kurzfristige Notfalleinsätze und technische Unterstützung im kombinierten Verkehr.</p><a class="sc-button" href="kontakt.html">Einsatz anfragen ↗</a></div><aside><b>5</b><span>Leistungsbereiche</span><b>24/7</b><span>Notfallkoordination</span><b>DE</b><span>Bundesweite Einsätze</span></aside></section><section class="sc-page-intro"><p class="sc-kicker">Im Detail</p><h2>Passende Unterstützung für planmäßige und kurzfristige Aufgaben.</h2><p>RT Rail Time verbindet professionelle Wagenmeister-Dienstleistungen mit schneller Reaktionsfähigkeit und standardisierter Ausrüstung. Die einzelnen Leistungsbereiche können abhängig von Aufgabenstellung und Einsatzort separat oder miteinander kombiniert angefragt werden.</p></section><nav class="sc-service-menu" aria-label="Leistungsbereiche"><?php foreach($rt['services'] as $i=>$service): ?><a data-service-tile href="#<?= $service['slug'] ?>"><img src="<?= rt_image($rt['assets']['service_images'][$i]) ?>" alt="<?= htmlspecialchars($service['title'],ENT_QUOTES,'UTF-8') ?>"><span>0<?= $i+1 ?></span><h3><?= $service['title'] ?></h3></a><?php endforeach ?></nav><section class="sc-accordion"><header><p class="sc-kicker">Leistungen im Detail</p><h2>Ein Ansprechpartner. Fünf Leistungsbereiche.</h2></header><?php foreach($rt['services'] as $i=>$service): ?><article id="<?= $service['slug'] ?>" data-accordion-item><button type="button" aria-expanded="false"><span>0<?= $i+1 ?></span><strong><?= $service['title'] ?></strong><i class="accordion-plus">+</i></button><div data-panel><div class="sc-panel"><img src="<?= rt_image($rt['assets']['service_images'][$i]) ?>" alt="<?= htmlspecialchars($service['title'],ENT_QUOTES,'UTF-8') ?>"><div><h3><?= $service['title'] ?></h3><p><?= $service['copy'] ?></p><a href="kontakt.html">Einsatz anfragen →</a></div></div></div></article><?php endforeach ?></section><section class="sc-process"><p class="sc-kicker">Ablauf</p><h2>Von der Anfrage bis zur Rückmeldung.</h2><div><?php foreach($rt['process'] as $i=>$step): ?><article><b>0<?= $i+1 ?></b><p><?= $step ?></p></article><?php endforeach ?></div></section><?php rt2_emergency($rt); ?></main><?php rt_footer($rt); rt_document_end(); }

function rt2_about(): void { $rt=rt_document_start('Über uns',2); ?>
<main class="sc-subpage"><section class="sc-page-hero" style="--image:url('<?= rt_image('s3.jpg') ?>')"><div><p class="sc-kicker">Ihr Partner im Eisenbahnbetrieb</p><h1>Über RT Rail Time GmbH</h1><p>Kompetent, flexibel und mit höchstem Anspruch an Sicherheit, Qualität und Kundenzufriedenheit.</p><a class="sc-button" href="kontakt.html">Einsatz anfragen ↗</a></div><aside><b>56+</b><span>Erfahrene Wagenmeister</span><b>24/7</b><span>Notfalldienst</span><b>DE</b><span>Bundesweit verfügbar</span></aside></section><section class="sc-content-split"><div><p class="sc-kicker">Im Detail</p><h2>Maßgeschneiderte Lösungen für den Eisenbahngüterverkehr.</h2><p>Die RT Rail Time GmbH ist Ihr kompetenter und flexibler Partner für Wagenmeister-Dienstleistungen im Eisenbahngüterverkehr. Mit hohem Anspruch an Sicherheit und Qualität bieten wir maßgeschneiderte Lösungen für unterschiedliche Herausforderungen im Bereich der Wagenmeisterdienstleistungen.</p><p>Unser Handeln ist auf die Zufriedenheit unserer Kunden ausgerichtet. Präzise Arbeitsweise, zuverlässige Kommunikation und schnelle Reaktion bilden die Grundlage unserer Zusammenarbeit.</p></div><img src="<?= rt_image('s1.jpg') ?>" alt="Wagenmeister von RT Rail Time"></section><section class="sc-values"><p class="sc-kicker">Unsere Philosophie</p><h2>Vertrauen entsteht durch transparente und zuverlässige Zusammenarbeit.</h2><div><article><b>01</b><h3>Sicherheit &amp; Qualität</h3><p>Nachhaltiges Qualitätsmanagement unterstützt Leistungen auf hohem fachlichem Niveau.</p></article><article><b>02</b><h3>Transparenz</h3><p>Klare Abstimmung und nachvollziehbare Kommunikation schaffen Vertrauen.</p></article><article><b>03</b><h3>Flexibilität</h3><p>Kurze Reaktionszeiten ermöglichen auch die Bearbeitung kurzfristiger Kundenanfragen.</p></article></div></section><section class="sc-process"><p class="sc-kicker">Zusammenarbeit</p><h2>Von der Anfrage bis zum zuverlässig ausgeführten Einsatz.</h2><div><?php foreach($rt['process'] as $i=>$step): ?><article><b>0<?= $i+1 ?></b><p><?= $step ?></p></article><?php endforeach ?></div></section><?php rt2_emergency($rt); ?></main><?php rt_footer($rt); rt_document_end(); }

function rt2_contact(): void { $rt=rt_document_start('Kontakt',2); ?>
<main class="sc-subpage"><section class="sc-page-hero" style="--image:url('<?= rt_image('s1.jpg') ?>')"><div><p class="sc-kicker">Kontakt &amp; Einsatzanfrage</p><h1>Direkt erreichbar. Deutschlandweit im Einsatz.</h1><p>Ob planbare Wagenmeister-Dienstleistung oder kurzfristiger Notfalleinsatz: Teilen Sie uns Einsatzort, gewünschte Leistung und Zeitpunkt mit.</p><a class="sc-button" href="tel:<?= $rt['phone_href'] ?>"><?= $rt['phone'] ?> ↗</a></div><aside><b>24/7</b><span>Notfalldienst</span><b>56+</b><span>Erfahrene Wagenmeister</span><b>DE</b><span>Bundesweit im Einsatz</span></aside></section><section class="sc-contact"><div><p class="sc-kicker">Ihre Anfrage</p><h2>Schnelle Abstimmung für einen sicheren Eisenbahnbetrieb.</h2><p>Je vollständiger die Einsatzangaben sind, desto schneller können wir Ihre Anfrage einordnen und bearbeiten.</p><ul><li><strong>Notfalldienst 24/7</strong><a href="tel:<?= $rt['phone_href'] ?>"><?= $rt['phone'] ?></a></li><li><strong>E-Mail &amp; Einsatzanfrage</strong><a href="mailto:<?= $rt['email'] ?>"><?= $rt['email'] ?></a></li><li><strong>Firmensitz</strong><span><?= $rt['address'] ?></span></li></ul></div><form action="mailto:<?= $rt['email'] ?>" method="post" enctype="text/plain"><label>Name<input name="Name" required></label><label>E-Mail<input name="E-Mail" type="email" required></label><label>Telefon<input name="Telefon" type="tel"></label><label>Einsatzort<input name="Einsatzort"></label><label class="full">Gewünschte Leistung<select name="Leistung"><?php foreach($rt['services'] as $service): ?><option><?= $service['title'] ?></option><?php endforeach ?></select></label><label class="full">Nachricht<textarea name="Nachricht" rows="6" required></textarea></label><button class="sc-button full" type="submit">Anfrage per E-Mail vorbereiten ↗</button></form></section><?php rt2_emergency($rt); ?></main><?php rt_footer($rt); rt_document_end(); }

function rt2_legal(string $type): void { $rt=rt_document_start($type==='imprint'?'Impressum':'Datenschutzerklärung',2); $imprint=$type==='imprint'; ?>
<main class="sc-subpage"><section class="sc-legal-hero"><p class="sc-kicker">Rechtliches</p><h1><?= $imprint?'Impressum':'Datenschutzerklärung' ?></h1></section><article class="sc-legal"><?php if($imprint): ?><h2>Angaben gemäß § 5 TMG</h2><p>Handelsregister:</p><p>Registergericht:</p><p><strong>Vertreten durch:</strong></p><h2>Kontakt</h2><p>Telefon: <?= $rt['phone'] ?><br>E-Mail: <?= $rt['email'] ?></p><h2>Umsatzsteuer-ID</h2><h2>Angaben zur Berufshaftpflichtversicherung</h2><p><strong>Name und Sitz des Versicherers:</strong></p><h2>Verbraucherstreitbeilegung/Universalschlichtungsstelle</h2><p>Wir sind nicht bereit oder verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.</p><h2>Haftung für Inhalte</h2><p>Als Diensteanbieter sind wir gemäß § 7 Abs. 1 TMG für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich.</p><h2>Haftung für Links</h2><p>Unser Angebot enthält Links zu externen Websites Dritter, auf deren Inhalte wir keinen Einfluss haben.</p><h2>Urheberrecht</h2><p>Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht.</p><?php else: ?><h2>Datenschutz auf einen Blick</h2><h3>Allgemeine Hinweise</h3><p>Die folgenden Hinweise geben einen einfachen Überblick darüber, was mit Ihren personenbezogenen Daten passiert, wenn Sie diese Website besuchen.</p><h2>Datenerfassung auf dieser Website</h2><h3>Wer ist verantwortlich für die Datenerfassung?</h3><p>Die Datenverarbeitung auf dieser Website erfolgt durch den Websitebetreiber.</p><h3>Wie erfassen wir Ihre Daten?</h3><p>Ihre Daten werden zum einen dadurch erhoben, dass Sie uns diese mitteilen. Hierbei kann es sich beispielsweise um Daten handeln, die Sie in ein Kontaktformular eingeben.</p><h3>Wofür nutzen wir Ihre Daten?</h3><p>Ein Teil der Daten wird erhoben, um eine fehlerfreie Bereitstellung der Website zu gewährleisten.</p><h2>Allgemeine Hinweise und Pflichtinformationen</h2><p>Die Betreiber dieser Seiten nehmen den Schutz Ihrer persönlichen Daten sehr ernst und behandeln personenbezogene Daten vertraulich.</p><h2>Kontaktformular</h2><p>Wenn Sie uns per Kontaktformular Anfragen zukommen lassen, werden Ihre Angaben zwecks Bearbeitung der Anfrage gespeichert und verarbeitet.</p><?php endif ?></article></main><?php rt_footer($rt); rt_document_end(); }
