<?php
require_once __DIR__ . '/segments.php';

function rt_services(int $theme): void {
    $rt = rt_document_start('Leistungen', $theme);
    $serviceImages = rt_service_images_for_theme($rt, $theme); ?>
<main class="pt-20 bg-gray-100"><section class="rt-section bg-gray-900 text-white"><p class="rt-kicker">Unsere Leistungen</p><h1 class="rt-title">Leistungen für sichere Abläufe im Eisenbahngüterverkehr</h1><p class="max-w-3xl leading-relaxed text-gray-300">Professionelle Wagenmeister-Dienstleistungen, kurzfristige Notfalleinsätze und technische Unterstützung im kombinierten Verkehr – klar strukturiert, bundesweit verfügbar und auf die konkrete Einsatzlage abgestimmt.</p></section><section class="rt-section"><p class="rt-kicker">Leistungsbereiche</p><h2 class="rt-title">Fünf Leistungen. Ein verlässlicher Ansprechpartner.</h2><div class="grid gap-4 md:grid-cols-2 lg:grid-cols-5"><?php foreach ($rt['services'] as $i => $service): ?><a data-service-tile href="#<?= $service['slug'] ?>" class="group relative min-h-64 overflow-hidden bg-gray-900 text-white"><img class="absolute inset-0 h-full w-full object-cover opacity-55 transition duration-500 group-hover:scale-105" src="<?= rt_image($serviceImages[$i]) ?>" alt="<?= htmlspecialchars($service['title'], ENT_QUOTES, 'UTF-8') ?>" loading="lazy" decoding="async"><span class="absolute inset-0 bg-gradient-to-t from-black via-transparent"></span><div class="absolute inset-x-5 bottom-5"><b class="text-red-400">0<?= $i + 1 ?></b><h3 class="mt-2 text-xl font-bold leading-tight"><?= $service['title'] ?></h3></div></a><?php endforeach ?></div></section><section class="rt-section bg-gray-900 text-white"><p class="rt-kicker">Leistungen im Detail</p><div class="mt-10 border-t border-gray-700"><?php foreach ($rt['services'] as $i => $service): ?><article id="<?= $service['slug'] ?>" data-accordion-item class="border-b border-gray-700"><button class="flex w-full items-center gap-5 py-6 text-left" aria-expanded="false"><span class="text-sm font-bold text-red-500">0<?= $i + 1 ?></span><strong class="flex-1 text-xl md:text-3xl"><?= $service['title'] ?></strong><span class="accordion-plus text-3xl font-light">+</span></button><div data-panel class="accordion-panel max-h-0 overflow-hidden"><div class="grid gap-8 pb-8 md:grid-cols-2"><img class="h-64 w-full object-cover" src="<?= rt_image($serviceImages[$i]) ?>" alt="<?= htmlspecialchars($service['title'], ENT_QUOTES, 'UTF-8') ?>" loading="lazy" decoding="async"><div><p class="leading-relaxed text-gray-300"><?= $service['copy'] ?></p><h4 class="mt-6 font-bold">Typischer Ablauf</h4><ol class="mt-3 space-y-2 text-sm text-gray-400"><li>01 · Anfrage und Einsatzdaten aufnehmen</li><li>02 · Qualifikation und Ausrüstung abstimmen</li><li>03 · Einsatz vor Ort durchführen</li><li>04 · Befund und Rückmeldung dokumentieren</li></ol><a class="rt-button mt-6" href="kontakt.html">Einsatz anfragen →</a></div></div></div></article><?php endforeach ?></div></section></main>
<?php rt_footer($rt); rt_document_end();
}

function rt_contact(int $theme): void {
    $rt = rt_document_start('Kontakt', $theme); ?>
<main class="pt-20"><section class="rt-split bg-gray-900 text-white"><img src="<?= rt_image($rt['assets']['team_image']) ?>" alt="Rail Time Kontakt"><div><p class="rt-kicker">Kontakt &amp; Einsatzanfrage</p><h1 class="rt-title">Direkt erreichbar. Deutschlandweit im Einsatz.</h1><p class="leading-relaxed text-gray-300">Ob planbare Wagenmeister-Dienstleistung oder kurzfristiger Notfalleinsatz: Teilen Sie uns Einsatzort, gewünschte Leistung und Zeitpunkt mit.</p></div></section><section class="rt-section bg-gray-100"><div class="grid gap-16 lg:grid-cols-2"><div><p class="rt-kicker">Kontaktformular</p><h2 class="rt-title">Schildern Sie uns Ihren geplanten oder dringenden Einsatz.</h2><p class="rt-lead">Je vollständiger die Einsatzangaben sind, desto schneller können wir Ihre Anfrage einordnen und bearbeiten.</p><p class="mt-8 font-bold"><a href="tel:<?= $rt['phone_href'] ?>"><?= $rt['phone'] ?></a><br><a href="mailto:<?= $rt['email'] ?>"><?= $rt['email'] ?></a></p></div><form class="grid gap-4 bg-white p-6 shadow-xl" action="mailto:<?= $rt['email'] ?>" method="post" enctype="text/plain"><label class="text-sm font-bold">Name<input class="mt-2 w-full border border-gray-300 p-3" name="Name" required></label><label class="text-sm font-bold">E-Mail<input class="mt-2 w-full border border-gray-300 p-3" type="email" name="E-Mail" required></label><label class="text-sm font-bold">Telefon<input class="mt-2 w-full border border-gray-300 p-3" type="tel" name="Telefon"></label><label class="text-sm font-bold">Gewünschte Leistung<select class="mt-2 w-full border border-gray-300 p-3" name="Leistung"><?php foreach ($rt['services'] as $service): ?><option><?= $service['title'] ?></option><?php endforeach ?></select></label><label class="text-sm font-bold">Einsatzort<input class="mt-2 w-full border border-gray-300 p-3" name="Einsatzort"></label><label class="text-sm font-bold">Nachricht<textarea class="mt-2 w-full border border-gray-300 p-3" rows="6" name="Nachricht" required></textarea></label><button class="rt-button justify-center border-0" type="submit">Anfrage per E-Mail vorbereiten →</button></form></div></section><?php rt_segment_emergency($rt); ?></main>
<?php rt_footer($rt); rt_document_end();
}

function rt_about(int $theme): void {
    $rt = rt_document_start('Über uns', $theme); ?>
<main class="pt-20"><section class="rt-split bg-gray-900 text-white"><img src="<?= rt_image('s4.jpg') ?>" alt="Rail Time im Einsatz"><div><p class="rt-kicker">Ihr Partner im Eisenbahnbetrieb</p><h1 class="rt-title">Über RT Rail Time GmbH</h1><p class="leading-relaxed text-gray-300">Die RT Rail Time GmbH ist Ihr kompetenter und flexibler Partner für Wagenmeister-Dienstleistungen im Eisenbahngüterverkehr.</p><a class="rt-button mt-6" href="kontakt.html">Einsatz anfragen →</a></div></section><section class="rt-section"><p class="rt-kicker">Im Detail</p><h2 class="rt-title">Maßgeschneiderte Lösungen für den Eisenbahngüterverkehr.</h2><div class="grid gap-10 lg:grid-cols-2"><p class="rt-lead">Die RT Rail Time GmbH ist Ihr kompetenter und flexibler Partner für Wagenmeister-Dienstleistungen im Eisenbahngüterverkehr. Mit hohem Anspruch an Sicherheit und Qualität bieten wir maßgeschneiderte Lösungen für unterschiedliche Herausforderungen im Bereich der Wagenmeisterdienstleistungen.</p><p class="rt-lead">Unser Handeln ist auf die Zufriedenheit unserer Kunden ausgerichtet. Präzise Arbeitsweise, zuverlässige Kommunikation und schnelle Reaktion bilden die Grundlage unserer Zusammenarbeit.</p></div></section><section class="rt-section bg-gray-900 text-white"><p class="rt-kicker">Unsere Philosophie</p><h2 class="rt-title">Vertrauen entsteht durch transparente und zuverlässige Zusammenarbeit.</h2><div class="grid gap-4 md:grid-cols-3"><article class="bg-gray-800 p-6"><h3 class="text-xl font-bold">Sicherheit &amp; Qualität</h3><p class="mt-3 text-gray-300">Nachhaltiges Qualitätsmanagement unterstützt Leistungen auf hohem fachlichem Niveau.</p></article><article class="bg-gray-800 p-6"><h3 class="text-xl font-bold">Transparenz</h3><p class="mt-3 text-gray-300">Klare Abstimmung und nachvollziehbare Kommunikation schaffen Vertrauen.</p></article><article class="bg-gray-800 p-6"><h3 class="text-xl font-bold">Flexibilität</h3><p class="mt-3 text-gray-300">Kurze Reaktionszeiten ermöglichen auch die Bearbeitung kurzfristiger Kundenanfragen.</p></article></div></section><?php rt_segment_process($rt); rt_segment_emergency($rt); ?></main>
<?php rt_footer($rt); rt_document_end();
}

function rt_imprint(int $theme): void {
    $rt = rt_document_start('Impressum', $theme); ?>
<main class="pt-20"><section class="rt-section bg-gray-900 text-white"><p class="rt-kicker">Impressum</p><h1 class="rt-title">Angaben gemäß § 5 TMG</h1></section><article class="rt-section bg-gray-100"><div class="mx-auto max-w-4xl space-y-6 leading-relaxed text-gray-700"><p>Handelsregister:</p><p>Registergericht:</p><p><strong>Vertreten durch:</strong></p><h2 class="text-3xl font-bold text-gray-900">Kontakt</h2><h2 class="text-3xl font-bold text-gray-900">Umsatzsteuer-ID</h2><h2 class="text-3xl font-bold text-gray-900">Angaben zur Berufshaftpflichtversicherung</h2><p><strong>Name und Sitz des Versicherers:</strong></p><h2 class="text-3xl font-bold text-gray-900">Verbraucherstreitbeilegung/Universalschlichtungsstelle</h2><p>Wir sind nicht bereit oder verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.</p><h2 class="text-3xl font-bold text-gray-900">Haftung für Inhalte</h2><p>Als Diensteanbieter sind wir gemäß § 7 Abs. 1 TMG für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach §§ 8 bis 10 TMG sind wir als Diensteanbieter jedoch nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen.</p><h2 class="text-3xl font-bold text-gray-900">Haftung für Links</h2><p>Unser Angebot enthält Links zu externen Websites Dritter, auf deren Inhalte wir keinen Einfluss haben.</p><h2 class="text-3xl font-bold text-gray-900">Urheberrecht</h2><p>Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht.</p></div></article></main>
<?php rt_footer($rt); rt_document_end();
}

function rt_privacy(int $theme): void {
    $rt = rt_document_start('Datenschutzerklärung', $theme); ?>
<main class="pt-20"><section class="rt-section bg-gray-900 text-white"><p class="rt-kicker">Datenschutzerklärung</p><h1 class="rt-title">Datenschutz auf einen Blick</h1></section><article class="rt-section bg-gray-100"><div class="mx-auto max-w-4xl space-y-6 leading-relaxed text-gray-700"><h2 class="text-3xl font-bold text-gray-900">Allgemeine Hinweise</h2><p>Die folgenden Hinweise geben einen einfachen Überblick darüber, was mit Ihren personenbezogenen Daten passiert, wenn Sie diese Website besuchen.</p><h2 class="text-3xl font-bold text-gray-900">Datenerfassung auf dieser Website</h2><h3 class="text-xl font-bold text-gray-900">Wer ist verantwortlich für die Datenerfassung auf dieser Website?</h3><p>Die Datenverarbeitung auf dieser Website erfolgt durch den Websitebetreiber.</p><h3 class="text-xl font-bold text-gray-900">Wie erfassen wir Ihre Daten?</h3><p>Ihre Daten werden zum einen dadurch erhoben, dass Sie uns diese mitteilen. Hierbei kann es sich beispielsweise um Daten handeln, die Sie in ein Kontaktformular eingeben.</p><h3 class="text-xl font-bold text-gray-900">Wofür nutzen wir Ihre Daten?</h3><p>Ein Teil der Daten wird erhoben, um eine fehlerfreie Bereitstellung der Website zu gewährleisten.</p><h2 class="text-3xl font-bold text-gray-900">Allgemeine Hinweise und Pflichtinformationen</h2><p>Die Betreiber dieser Seiten nehmen den Schutz Ihrer persönlichen Daten sehr ernst und behandeln personenbezogene Daten vertraulich.</p><h2 class="text-3xl font-bold text-gray-900">Kontaktformular</h2><p>Wenn Sie uns per Kontaktformular Anfragen zukommen lassen, werden Ihre Angaben zwecks Bearbeitung der Anfrage gespeichert und verarbeitet.</p><p>Den vollständigen Originaltext finden Sie auf der aktuellen Live-Seite.</p></div></article></main>
<?php rt_footer($rt); rt_document_end();
}
